import Head from "next/head";
import React, { useEffect, useState } from "react";
import Home5About from "../components/about/Home5About";
import Banner5 from "../components/banner/Banner5";
import Home5Blog from "../components/blog/Home5Blog";
import Home5Services from "../components/about/Home5Service"
import InstagramFeed from "../components/common/InstagramFeed";
import Preloader from "../components/common/Preloader";
import Home5Counter from "../components/countdown/Home5Counter";
import Home5Destination from "../components/destination/Home5Destination";
import Home5Feature from "../components/feature/Home5Feature";
import Footer1 from "../components/footer/Footer1";
import Header5 from "../components/header/Header5";
import Home5Package from "../components/package/Home5Package";
import Home5Partnar from "../components/sponsor/Home5Partnar";
import Home5Testimonial from "../components/testimonial/Home5Testimonial";

function IndexWildlife() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 3000);
  }, []);
  return (
    <>
      {!loading ? (
        <>
        <Head>
        <title>Loading</title>
        <meta name="description" content="SimbaHeartTravels | Tourism | Africa | Zanzibar | Tanzania" />
        <link rel="icon" href="assets/images/icons/logo-simba.png" />
      </Head>
        <Preloader loader="home5preloader" />
        
        </>
      ) : (
        <>
        <Head>
        <title>Simba Hearts Travels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-simba.png" />
      </Head>
          <Header5 />
          <Banner5 />
          <Home5About />
          <Home5Services/>
          <Home5Package /> 
          <Home5Counter />
          {/* <Home5Testimonial /> */}
          <Home5Partnar />
          {/* <Home5Feature />
          <Home5Destination />
          <Home5Blog /> */}
          <InstagramFeed type="wildInstagram" />
          <Footer1 />
        </>
      )}
    </>
  );
}

export default IndexWildlife;
